### ISSUE TITLE
Panic: attempt to multiply with overflow

### ISSUE THREAD

**Issue by tacuna** [hauju/scd4x-rs#2]
When running the example i get

```
serial: [retracted]
Waiting for first measurement... (5 sec)
thread 'main' panicked at 'attempt to multiply with overflow', [retracted]/scd4x-rs/src/scd4x.rs:77:29
```
Seems like temperature: '((((21875 * temperature) >> 13) - 45000) as f32) / 1000.0' is not safe.

**Comment by tacuna** [comment]
This seem to work and gives plausible results

        Ok(SensorData {
            co2,
            temperature: temperature as f32 * 175_f32 / 65536_f32 - 45_f32,
            humidity: humidity as f32 * 100_f32 / 65536_f32,
        })
        
Taken from https://github.com/Sensirion/raspberry-pi-i2c-scd4x/blob/master/scd4x_i2c.c

**Comment by hauju** [comment]
Looks good, I will change it in the next few days.
